### ISSUE TITLE
Resource not found

### ISSUE THREAD

**Issue by Os3r3um** [qazbnm456/awesome-web-security#1]
Hi buddy, 

This resource can't be reached. Link is broken or contains some non standard chars. 

Rails Security - Written by @qazbnm456.

Please, can you double check the initial link?

Thanks.

**Comment by qazbnm456** [comment]
@Os3r3um Hi, there. I'm gonna to revise some content of the paper and translate it into English recently, since the original paper is written in Chinese. I'll update the link after I push the final touch of that. Thanks 😃

**Comment by Os3r3um** [comment]
Right. No worries buddy. 

Meanwhile, if you have a working link regards that pdf, even in Chinese,  won't be a big drama for me. I probably can try to use google translate until you'll have the english version published :)

Cheers.

**Comment by qazbnm456** [comment]
@Os3r3um Okay, here is the link: [Rails Security (上) | WooYun知识库](https://drops.secquan.org/web/12750). 👍

**Comment by Os3r3um** [comment]
Awesome. Thanks! :+1:

**Comment by Os3r3um** [comment]
Hi, I got another one which does not seem to be working. Please, can you have a look when you'll have some spare time? 

The XML Section -> http://www.freebuf.com/video/49961.html

Thanks!

**Comment by qazbnm456** [comment]
@Os3r3um Hi there, I get no problem seeing the content through the link. You may want to try again, and if you still have problem seeing that, here is the link to the slide: http://static.freebuf.com/2014/11/5-XML实体攻击：从内网探测到命令执行步步惊心-张天琪.pdf.
