### ISSUE TITLE
Change @UltimateHackers to @s0md3v

### ISSUE THREAD

**Issue by s0md3v** [qazbnm456/awesome-web-security#18]
Thanks for featuring my [XSStrike](https://github.com/s0md3v/XSStrike) in your list.

Well I changed my username recently and now its "s0md3v" and not "UltimateHackers" so it would be great if you can change that.

Thanks ^_^

**Comment by qazbnm456** [comment]
Hi @s0md3v, I've changed your username on the list per https://github.com/qazbnm456/awesome-web-security/commit/cc17d01dfd3d2c119e4c258d90dafee6d79b47c8. Thanks for noticing! 😄
