### ISSUE TITLE
Recommend a webshell management tool

### ISSUE THREAD

**Issue by WangYihang** [qazbnm456/awesome-web-security#5]
A webshell manager via terminal
Simple Usage : https://asciinema.org/a/130893
> https://github.com/WangYihang/Webshell-Sniper

**Comment by qazbnm456** [comment]
@WangYihang Thanks, I'll take a look at it recently. Looks promising!

**Comment by qazbnm456** [comment]
@WangYihang Added. Thank you! 👍
