### ISSUE TITLE
language

### ISSUE THREAD

**Issue by fzf404** [qazbnm456/awesome-web-security#64]
why the ‘Awesome Web Security - ZH .md’ is English.
a chinese study sad.
a japanese sad too.
QWQ

**Comment by qazbnm456** [comment]
Since it's extended from the English one, it contains both materials in English and Chinese. 😟 

You could contribute more to both Chinese and Japanese versions. 😆

**Comment by qazbnm456** [comment]
If you have another problem, please kindly open a new issue. Thanks!
